#!/usr/bin/env python3

import subprocess
import mplgui
import os
import sys

test_dir = os.path.join(
    mplgui.SOURCE_DIRECTORY,
    'tests',
)

curdir = os.getcwd()
os.chdir(test_dir)
try:
    p = subprocess.run(
        ['python3', 'run_all_tests.py'],
        check = True,
        text = True,
        stdout = subprocess.PIPE,
        stderr = subprocess.STDOUT,
    )
    if p.stdout and ('FAILED' in p.stdout or 'Traceback' in p.stdout):
        # This is a forgivable error, when we have no tests to run.
        if "can't open file " in p.stdout and "tests/run_all_tests.py" in p.stdout and "No such file or directory" in p.stdout:
            sys.exit(0)
        print(p.stdout)
        sys.exit(1)
except subprocess.CalledProcessError as e:
    print(e.returncode)
    print(e.output)
    sys.exit(1)

sys.exit(0)
